# Generated by Django 4.2.7 on 2025-05-23 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SarDataEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technology_type', models.CharField(db_index=True, default='', max_length=50)),
                ('system_check_date', models.DateField(blank=True, null=True)),
                ('test_date', models.DateField(blank=True, null=True)),
                ('tested_by', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('sample_no', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('sar_lab', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('rf_exposure_condition', models.CharField(blank=True, default='', max_length=100)),
                ('mode', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('dsi', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('distance_mm', models.FloatField(blank=True, null=True)),
                ('test_position', models.CharField(blank=True, default='', max_length=100)),
                ('channel', models.CharField(blank=True, default='', max_length=100)),
                ('frequency_mhz', models.FloatField(blank=True, null=True)),
                ('tune_up_limit', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('meas_power', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('measured_sar_1g', models.FloatField(blank=True, null=True)),
                ('scaled_sar_1g', models.FloatField(blank=True, null=True)),
                ('measured_sar_10g', models.FloatField(blank=True, null=True)),
                ('scaled_sar_10g', models.FloatField(blank=True, null=True)),
                ('step_size_mm', models.FloatField(blank=True, null=True)),
                ('dis_3db_peak_mm', models.FloatField(blank=True, null=True)),
                ('z_axis_ratio_percent', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'SAR Data Entry',
                'verbose_name_plural': 'SAR Data Entries',
            },
        ),
        migrations.CreateModel(
            name='TechnologyChannelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technology_type', models.CharField(db_index=True, max_length=50, unique=True)),
                ('channel_count', models.PositiveIntegerField()),
                ('config_locked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ChannelDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_number_ui', models.PositiveIntegerField()),
                ('ch_name', models.CharField(blank=True, default='', max_length=100)),
                ('frequency_mhz', models.FloatField(blank=True, null=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_details', to='tab.technologychannelconfig')),
            ],
        ),
    ]
