# Generated by Django 5.2.1 on 2025-05-31 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sardataentry',
            name='rb',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sardataentry',
            name='rb_position',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
